### ISSUE TITLE
Unable to intercept requests sent during pre-rendering in Next.js

### ISSUE THREAD

**Issue by ajfAfg** [kettanaito/msw#1340]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v18.3.0

### Reproduction repository

https://github.com/ajfAfg/msw-operation-research

### Reproduction steps

1. Run the following commands

```sh
git clone https://github.com/ajfAfg/msw-operation-research.git
cd msw-operation-research/nextjs-rest
npm install
npm run dev
```

2. Open http://localhost:3000

### Current behavior

In `src/pages/index.tsx`, `getServerSideProps` fetches data and outputs the received data to the console. Currently, the output is as follows.

```sh
server: {"answer":"yes","forced":false,"image":"https://yesno.wtf/assets/yes/14-b57c6dc03aa15a4b18f53eb50d6197ee.gif"}
```

The data being fetched here is as follows.

```sh
$ curl https://yesno.wtf/api
{"answer":"yes","forced":false,"image":"https://yesno.wtf/assets/yes/11-a23cbde4ae018bbda812d2d8b2b8fc6c.gif"}
```

### Expected behavior

The expected output is as follows, since the request is intercepted by the definition in `src/mocks/handlers.ts`.

```sh
server: {"foo":"bar"}
```

**Comment by AleskiWeb** [comment]
Does this discussion here provide any insight? https://github.com/mswjs/msw/discussions/1209 - I must admit, I too have issues with the initial requests but that may be my somewhat janky implementation and its not key for me personally that the initial SSR bit works

**Comment by kettanaito** [comment]
Hey, @ajfAfg. Thanks for reporting this. 

Could you please update to the latest `msw` version? You're using `0.44.1` while the latest published version if `0.48.2`. That's quite a lot of changes, which may have potentially fixed your issues too. 

Please update your reproduction repository and let me know if the issue is still there.

I've read through it and found no apparent reasons why server-side mocking wouldn't work. I can see your setup is based on the NextJS MSW template, which should be functional.

**Comment by watch-janick** [comment]
@kettanaito I've tested the NextJS MSW template and it doesn't work at all, I've reported it to them, but if you have any idea how to make it work, that would be awesome 😁 
https://github.com/vercel/next.js/issues/43221

Thanks!

**Comment by andykenward** [comment]
> @kettanaito I've tested the NextJS MSW template and it doesn't work at all, I've reported it to them, but if you have any idea how to make it work, that would be awesome 😁 [vercel/next.js#43221](https://github.com/vercel/next.js/issues/43221)
> 
> Thanks!

@watch-janick The NextJs MSW example is using an exact version of msw `0.47.3` and doesn't install the latest version. If you update it to the latest version `0.49.0` it should work. I've fixed the example in this PR https://github.com/vercel/next.js/pull/43224

**Comment by kettanaito** [comment]
Another thing to consider is that MSW doesn't officially support Node.js 18. You can follow the progress in #1388. If I were to look into these changes, I'd use Node.js 17.

**Comment by kettanaito** [comment]
Thanks for fixing the template, @andykenward! Does it function as expected now both in terms of client-side and server-side interception (i.e. this issue is resolved)?

**Comment by andykenward** [comment]
> Thanks for fixing the template, @andykenward! Does it function as expected now both in terms of client-side and server-side interception (i.e. this issue is resolved)?

@kettanaito I've not checked the "reproduction repository" https://github.com/ajfAfg/msw-operation-research in this issue. Will do that now and also try the latest msw `0.49.0`. But I wont use node 18.

**Comment by andykenward** [comment]
@kettanaito The issue with NextJS and MSW being enabled to intercept client side requests still exists. 

Using 
node: `v16.18.1`
npm: `8.19.2`

I've managed to fix the issue. But it involved changing a few things in the Next.JS setup. Had to enable webpack experiments of topLevelAwait along with changing TypeScript `tsconfig.json` `target` from `ES5` to `ESNext`

So I could change `_app.tsx` from using
```tsx
  require('../mocks')
```
to
```tsx
  await import('../mocks')
```

You can see all the changes in this commit https://github.com/andykenward/next-with-msw/commit/91d9bbda12baff864913dc9eb95e7d921d75fb27

To reproduce the client side error before the above changes, checkout commit https://github.com/andykenward/next-with-msw/commit/3d00db8f66b12e5496881b18bbd3b903a479f0df

You should get this error on the server from the client side fetch happening in a `useEffect`
```
error - FetchError: request to https://my.backend/book failed, reason: getaddrinfo ENOTFOUND my.backend
    at ClientRequest.<anonymous> (/Users/andykenward/Documents/github/andykenward/next-with-msw/with-msw-pages/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  page: '/'
}
```


I've started to also look into using the new Next.JS app directory changes they are currently working on. But haven't managed to get it working yet. https://github.com/andykenward/next-with-msw/tree/main/with-msw-app . Will probably hold off until msw native fetch support version is released.

**Comment by andykenward** [comment]
I've downgraded from `ESNext` to `ES2017` to support more browsers https://github.com/andykenward/next-with-msw/commit/8308df208bd2c8bdac45e6e38eaa5e57cb89e138 .

I think at the moment the only other way to avoid changing these configurations is to run a total [custom next.js server](https://nextjs.org/docs/advanced-features/custom-server) when you want to use MSW

**Comment by Wekios** [comment]
@andykenward thanks man!

We've just recently protected our API route and we didn't put auth headers on the request that went out to that API so we got 2 nasty surprises:
- Some of our static built pages (especially those created getStaticPaths + getStaticProps) were going out to our real API instead of being intercepted.
- The occurrences were random, sometimes it works, but after navigating between pages it fails.

Implementing your solution works for now!

**Comment by philwolstenholme** [comment]
@andykenward re: the `app` directory, https://twitter.com/housecor/status/1592718956288413696 suggests you can get it working by putting the mocks import _inside_ the `RootLayout` exported function, whereas in your repo it's in the `layout.tsx` file but not inside the exported function.

I tried that and couldn't get it working, but thought I'd share this just in case you have more luck with it than I did!

**Comment by andykenward** [comment]
> @andykenward re: the `app` directory, https://twitter.com/housecor/status/1592718956288413696 suggests you can get it working by putting the mocks import _inside_ the `RootLayout` exported function, whereas in your repo it's in the `layout.tsx` file but not inside the exported function.
> 
> I tried that and couldn't get it working, but thought I'd share this just in case you have more luck with it than I did!

@philwolstenholme I've not managed to get msw working using the `app` directory Next.js feature. I've found that layout components render after the page component, when using `next dev`. So any data fetching in a page that needs msw already loaded would fail. But even moving any MSW logic to a page component didn't help in getting MSW working.

I have found that using any top level async, throws any error in `next-swc-loader`. Which my fix uses.
```
top level await requires target to es2017 or higher and topLevelAwait:true for ecmascript
```
This error only threw when i removed the if statement check.
```tsx
// if (process.env.NEXT_PUBLIC_API_MOCKING === 'enabled') {
  await import('../mocks')
// }
```

I don' t think you are able to change the compile output target at the moment when using the `app` directory in Next.js.

A working example repo from the tweet author would be helpful. 

I've found using `await import`  instead of `require` was the only reliable & consistent way to have MSW loaded before fetch requests. Otherwise i was getting flaky tests etc.

**Comment by philwolstenholme** [comment]
Fingers crossed for `app` directory becoming stable soon, and then that giving the Vercel team (with possible help from MSW) the chance and stability to come back to the Next `with-msw` example and work through the dynamic import issues and the 'working inside the `app` directory' issues 🤞

**Comment by philwolstenholme** [comment]
I spoke to @coryhouse on Twitter and it turns out I'd misunderstood and he _hadn't_ got it working:

https://twitter.com/housecor/status/1628058885490675712

**Comment by sanjsharma** [comment]
Anyone got this working in Next13 ?

**Comment by kristojorg** [comment]
I am seeing this error in NextJS 13 when using the `pages` directory. The MSW server is unable to intercept server-side requests reliably. You can reproduce this by running the official [with-msw](https://github.com/vercel/next.js/tree/canary/examples/with-msw) example. It will throw this error from the request in `getServerSideProps`:

```
 ⨯ TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getServerSideProps (webpack-internal:///./pages/index.tsx:88:17) {
  cause: Error: getaddrinfo ENOTFOUND my.backend
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'my.backend'
  },
  page: '/'
}
```

It also does not work if you upgrade the example to `msw@next`. 

In my own app, I see that server side requests are occasionally intercepted, but most times not.

I have also opened an issue in Next.js: https://github.com/vercel/next.js/issues/56608

**Comment by SalahAdDin** [comment]
This is the main issue with any implementation, event with the @kettanaito example.

**Comment by kettanaito** [comment]
## Update

I'm going to close this. The original issue involved the versions of Next.js and MSW that have long improved and don't exist anymore. Support for the latest Next.js is generally being worked on in https://github.com/mswjs/examples/pull/101 and sufficiently covers both server and client with a few issues that are fundamental to Next.js. Sadly, our collaboration with the Next.js hasn't yielded the resolution of those problems. As of now, I cannot recommend that usage example as lacks proper developer experience that people associate with MSW.
