### ISSUE TITLE
Error after upgrading to graphql 16.7.0: "Uncaught SyntaxError: Unexpected string"

### ISSUE THREAD

**Issue by oidualc** [kettanaito/msw#1643]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/oidualc/msw-graphql-issue

### Reproduction steps

- Download reproduction repository
- run `pnpm install`
- run `pnpm run dev`
- open http://localhost:5173

### Current behavior

Blank page and error on console `Uncaught SyntaxError: Unexpected string`.
This happens since upgrading graphql to 16.7.0, does not happen forcing the version to 16.6.0.

### Expected behavior

Page rendered correctly, no errors on console.

**Comment by SwagMuffinMcYoloPants** [comment]
I get the same issue too.  When i roll back to msw 0.40.2, it seems to work again.

**Comment by oidualc** [comment]
This seems to be caused by https://github.com/graphql/graphql-js/pull/3887, and it's been reported multiple times on the graphql repo as it's causing problems for projects other than msw. For example:

- https://github.com/graphql/graphql-js/issues/3918
- https://github.com/graphql/graphql-js/issues/3919
- https://github.com/graphql/graphql-js/issues/3920
- https://github.com/graphql/graphql-js/issues/3921

**Comment by SwagMuffinMcYoloPants** [comment]
@oidualc I'm using REST and it's exhibiting the same problem.  I can make a repo if you want.

**Comment by thepassle** [comment]
Repo wont be needed, but thank you for offering :) The issue has already been identified, waiting for action on the side of the graphql maintainers.

**Comment by SwagMuffinMcYoloPants** [comment]
ah, but the issue I'm seeing the issue with REST and would it be caused by the same issue?  Or is it something completely different?

**Comment by oidualc** [comment]
Closing the issue as it was resolved upstream with https://github.com/graphql/graphql-js/pull/3923. For future reference for anyone who will encounter this bug, just make sure to upgrade the graphql sub-dependency at least to https://github.com/graphql/graphql-js/releases/tag/v16.7.1.

**Comment by EhabSalah** [comment]
This could be an error introduced with version 16.7.0 of the graphql package. Please downgrade for 16.6.0 for now, we are looking into this.

**Comment by kristojorg** [comment]
@oidualc , is a newer version of graphql installed in `msw`? I just tried on `latest` and was still seeing this error. I don't believe `npm` provides a way (like yarn resolutions) to upgrade a sub-dependency. I tried installing latest `graphql` and this did not resolve the problem

**Comment by integratorivan** [comment]
@kristojorg hello! I have updated vite to the latest version (3.0.7 -> 4.4.7) and am updating msw - and the problem is solved

check this issue https://github.com/mswjs/msw/issues/1655

**Comment by kristojorg** [comment]
Thank you @integratorivan ! I'll give it a try : )
